name: Auto Deploy na VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Diagnose PHP
        shell: powershell
        run: |
          Write-Host "User:"
          whoami

          Write-Host "USERPROFILE:"
          Write-Host $env:USERPROFILE

          Write-Host "PHP path:"
          Test-Path "C:\Users\Administrator\.config\herd-lite\bin\php.exe"

          Write-Host "PHP command:"
          Get-Command php -ErrorAction SilentlyContinue

          Write-Host "PHP version:"
          php -v

      - name: Run Migrations and Cache
        shell: powershell
        run: |
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan migrate --force
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan config:cache
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan route:cache
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan view:cache
