name: Auto Deploy na VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: powershell
        run: |
          C:\Users\Administrator\.config\herd-lite\bin\composer.bat install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Migrations and Cache
        shell: powershell
        run: |
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan migrate --force
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan config:cache
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan route:cache
          & "C:\Users\Administrator\.config\herd-lite\bin\php.exe" artisan view:cache